# 说明路径可以使用/或\\，会统一转换
root:
  def_dirs:
    software_dir: D:/ws/apps
    shortcut_dir: '%USERPROFILE%\\Desktop\\scs'
  paths:
    - d:/ws/my-tools
    - d:/d-tmp
    - d:/ws/apps
    - d:/ws/git-github
    - d:/ws/git-other
    - d:/ws/jianguoyun_files
    - d:/ws/cached_files/clipcache
    - d:/ws/cached_files/jianguoyun
    - d:/ws/cached_files/wechat
    - d:/downloadss
    - d:/ws/vm-os
    - d:/ws/link_dir
    - ~/.ssh
    - ~/.m2
    - ~/desktop/sc
  envs:
    - name: JAVA_HOME
      value: D:/ws/apps/graalvm-jdk-21.0.6
      scope: user        # user | system
    - name: MAVEN_HOME
      value: D:/ws/apps/maven
      scope: user
    - name: PATH
      append:
        - D:/ws/apps/jdk8/bin
        - D:/ws/apps/maven/bin
      scope: user
  softwares:
    - name: VirtualBox
      dir_name: VirtualBox
    - name: Maven
      dir_name: apache-maven-3.9.9
    - name: chrome-extension-cookie-collector
      dir_name: chrome-extension-cookie-collector
  shortcuts:
    - name: hosts.lnk
      source: "C:/Windows/System32/drivers/etc/hosts"
      target: "hosts.lnk"
      gencmd: 'shortcut.exe /f:"%USERPROFILE%\\Desktop\\scs\\hosts.lnk" /a:c /t:"C:/Windows/System32/drivers/etc/hosts"'
