root:
  paths:
    - d:/ws/my-tools
    - d:/d-tmp
    - d:/ws/apps
    - d:/ws/git-github
    - d:/ws/git-other
    - d:/ws/jianguoyun_files
    - d:/ws/cached_files/clipcache
    - d:/ws/cached_files/jianguoyun
    - d:/ws/cached_files/wechat
    - d:/downloadss
    - d:/ws/vm-os
    - d:/ws/link_dir
    - ~/.ssh
    - ~/.m2
    - ~/desktop/sc
  envs:
    - name: JAVA_HOME
      value: D:/ws/apps/graalvm-jdk-21.0.6
      scope: user        # user | system
    - name: MAVEN_HOME
      value: D:/ws/apps/maven
      scope: user
    - name: PATH
      append:
        - D:/ws/apps/jdk8/bin
        - D:/ws/apps/maven/bin
      scope: user
  softwares:
    - name: VirtualBox
      root_dir: D:/ws/apps/VirtualBox
    - name: Maven
      root_dir: D:/ws/apps/apache-maven-3.6.3
  shortcuts:
    - name: hosts.lnk
      target: "C:/Windows/System32/drivers/etc/hosts"
      remark: 'shortcut.exe /f:"%USERPROFILE%\\Desktop\\hosts.lnk" /a:c /t:"C:/Windows/System32/drivers/etc/hosts"'
