name: Build Release

on:
  push:
    tags:
      - 'v*'

env:
  APP_NAME: "go-win-config-tool"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  Checkout code
      - uses: actions/checkout@v4

      #  Set VERSION from tag
      - name: Set VERSION env
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      #  Setup Node.js (for frontend)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      #  Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1"
      #  Install Wails CLI
      - name: Install Wails CLI
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      # Install frontend dependencies and build
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      #  Build Go + Wails app for multiple platforms
      - name: Build Go Binaries
        run: |
          wails version
          go mod tidy
          # Windows build
          GOOS=windows GOARCH=amd64 wails build -o ${{ env.APP_NAME }}-${{ env.VERSION }}-win.exe
          # Linux build
          # GOOS=linux GOARCH=amd64 wails build -o ${{ env.APP_NAME }}-${{ env.VERSION }}-linux
          cp ./build/bin/${{ env.APP_NAME }}-* ./build/
      #  Generate sha256
      - name: Generate SHA256
        run: |
          cd build
          sha256sum build/${{ env.APP_NAME }}-${{ env.VERSION }}-win.exe   > build/${{ env.APP_NAME }}-${{ env.VERSION }}-win.exe.sha256
          #sha256sum build/${{ env.APP_NAME }}-${{ env.VERSION }}-linux     > build/${{ env.APP_NAME }}-${{ env.VERSION }}-linux.sha256

      #  Upload Release Assets
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/${{ env.APP_NAME }}-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
